steps:
- name: 'ruby:2.4.6-alpine3.9'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gem install middleman \
    && bundle exec middleman build --clean
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://developers.allphins.com"]